services:
  p2p-node-3:
    image: 192.168.1.3:5000/chat-p2p:v1
    ports:
      - "6003:6000"
    stdin_open: true
    tty: true
    environment:
      - MY_PORT=6003
      - PEER_IP=p2p-node-4
      - PEER_PORT=6004

  p2p-node-4:
    image: 192.168.1.3:5000/chat-p2p:v1
    ports:
      - "6004:6000"
    stdin_open: true
    tty: true
    environment:
      - MY_PORT=6004
      - PEER_IP=192.168.200.17
      - PEER_PORT=6001