version: '3.8'

services:
  p2p-node-b:
    image: 192.168.1.3:5000/chat-p2p:v1 # Récupère l'image depuis VM3
    ports:
      - "6000:6000" # Expose le port 6000 de VM1
    stdin_open: true
    tty: true
    environment:
      - MY_PORT=6000          # J'écoute sur 6000
      - PEER_IP=192.168.1.3   # Je parle à la VM3
      - PEER_PORT=6000        # Sur son port 6000