services:
  # Client 1
  client-1:
    image: 192.168.200.17:5000/chat-app:v1
    command: python client.py
    stdin_open: true
    tty: true
    environment:
      - SERVER_HOST=192.168.200.17
      - SERVER_PORT=6000

  client-2:
    image: 192.168.200.17:5000/chat-app:v1
    command: python client.py
    stdin_open: true
    tty: true
    environment:
      - SERVER_HOST=192.168.200.17
      - SERVER_PORT=6000